//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bds256641637_dbEntities : DbContext
    {
        public bds256641637_dbEntities()
            : base("name=bds256641637_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<zhancaiw_category> zhancaiw_category { get; set; }
        public DbSet<zhancaiw_email> zhancaiw_email { get; set; }
        public DbSet<zhancaiw_feedback> zhancaiw_feedback { get; set; }
        public DbSet<zhancaiw_links> zhancaiw_links { get; set; }
        public DbSet<zhancaiw_look> zhancaiw_look { get; set; }
        public DbSet<zhancaiw_tanmu> zhancaiw_tanmu { get; set; }
        public DbSet<zhancaiw_user> zhancaiw_user { get; set; }
        public DbSet<zhancaiw_video> zhancaiw_video { get; set; }
        public DbSet<zhancaiw_vyw_links_user> zhancaiw_vyw_links_user { get; set; }
        public DbSet<zhancaiw_vyw_tanmu_video_user> zhancaiw_vyw_tanmu_video_user { get; set; }
    }
}
