//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zhancaiw_user
    {
        public int userID { get; set; }
        public string openID { get; set; }
        public string userName { get; set; }
        public string userPwd { get; set; }
        public string aover { get; set; }
        public string email { get; set; }
        public string lastIP { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> sex { get; set; }
        public string hobby { get; set; }
        public string introduce { get; set; }
        public string nickName { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<System.DateTime> lastTime { get; set; }
        public string activeToken { get; set; }
        public Nullable<System.DateTime> activeTime { get; set; }
        public Nullable<int> activeStatus { get; set; }
        public Nullable<System.DateTime> regTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
