//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zhancaiw_video
    {
        public int videoID { get; set; }
        public int userID { get; set; }
        public int sortID { get; set; }
        public string categoryID { get; set; }
        public string videoTitle { get; set; }
        public string videoCover { get; set; }
        public string videoUrl { get; set; }
        public string videoAuthor { get; set; }
        public string videoSourceUrl { get; set; }
        public string videoDescripe { get; set; }
        public Nullable<int> videoStatus { get; set; }
        public Nullable<int> clickCount { get; set; }
        public Nullable<bool> isRecommend { get; set; }
        public Nullable<System.DateTime> addTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<System.DateTime> releaseTime { get; set; }
    }
}
